import fs from 'node:fs/promises'
import path from 'node:path'
import { parse } from 'jsonc-parser'
import { afterEach, describe, expect, it } from 'vitest'
import { initializeProject } from '../src/initializer'
import { createTempDirectory } from './helpers'

const temporaryDirectories: string[] = []

async function createProject(): Promise<string> {
  const root: string = await createTempDirectory('initializer')
  temporaryDirectories.push(root)
  await fs.mkdir(path.join(root, 'config'), { recursive: true })
  await fs.writeFile(
    path.join(root, 'config', 'heft.json'),
    `{
  // SPFx rig configuration
  "extends": "@microsoft/spfx-web-build-rig/profiles/default/config/heft.json",
  "phasesByName": {
    "build": {
      "tasksByName": {
        "webpack": { "taskDependencies": ["typescript"] }
      }
    }
  }
}\n`,
    'utf8',
  )
  return root
}

async function createFreshSpfxProject(): Promise<string> {
  const root: string = await createTempDirectory('fresh spfx initializer')
  temporaryDirectories.push(root)
  await fs.mkdir(path.join(root, 'config'), { recursive: true })
  await fs.writeFile(
    path.join(root, 'config', 'rig.json'),
    `{
  // Generated by the SPFx Yeoman generator
  "$schema": "https://developer.microsoft.com/json-schemas/rig-package/rig.schema.json",
  "rigPackageName": "@microsoft/spfx-web-build-rig"
}
`,
    'utf8',
  )
  return root
}

afterEach(async (): Promise<void> => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory: string) =>
      fs.rm(directory, { force: true, recursive: true }),
    ),
  )
})

describe('initializeProject', (): void => {
  it('creates heft.json for a fresh SPFx project that only has rig.json', async (): Promise<void> => {
    const root: string = await createFreshSpfxProject()
    const result = await initializeProject({ cwd: root })

    expect(result.changedFiles).toEqual([
      'config/heft.json',
      'src/global.tailwind.css',
      '.gitignore',
    ])

    const config = parse(await fs.readFile(path.join(root, 'config', 'heft.json'), 'utf8'))
    expect(config.extends).toBe(
      '@microsoft/spfx-web-build-rig/profiles/default/config/heft.json',
    )
    expect(config.phasesByName.build.tasksByName.tailwind.taskPlugin).toMatchObject({
      pluginName: 'tailwind-plugin',
      pluginPackage: '@hmr-lukas/heft-tailwind-plugin',
      options: {},
    })
    expect(config.phasesByName.build.tasksByName.webpack.taskDependencies).toEqual(['tailwind'])
  })

  it('configures an SPFx project idempotently', async (): Promise<void> => {
    const root: string = await createProject()
    const first = await initializeProject({ cwd: root, prefix: 'tw', preflight: true })
    expect(first.changedFiles).toEqual([
      'config/heft.json',
      'src/global.tailwind.css',
      '.gitignore',
    ])

    const config = parse(await fs.readFile(path.join(root, 'config', 'heft.json'), 'utf8'))
    const tasks = config.phasesByName.build.tasksByName
    expect(tasks.tailwind.taskPlugin).toMatchObject({
      pluginName: 'tailwind-plugin',
      pluginPackage: '@hmr-lukas/heft-tailwind-plugin',
      options: { prefix: 'tw', preflight: true },
    })
    expect(tasks.webpack.taskDependencies).toEqual(['typescript', 'tailwind'])
    await expect(fs.readFile(path.join(root, 'src', 'global.tailwind.css'), 'utf8')).resolves.toBe(
      '@import "tailwindcss";\n',
    )
    await expect(fs.readFile(path.join(root, '.gitignore'), 'utf8')).resolves.toContain(
      'src/global.css',
    )

    const second = await initializeProject({ cwd: root, prefix: 'tw', preflight: true })
    expect(second.changedFiles).toEqual([])
  })

  it('supports dry runs without changing files', async (): Promise<void> => {
    const root: string = await createProject()
    const before: string = await fs.readFile(path.join(root, 'config', 'heft.json'), 'utf8')
    const result = await initializeProject({ cwd: root, dryRun: true })

    expect(result.changedFiles).toHaveLength(3)
    await expect(fs.readFile(path.join(root, 'config', 'heft.json'), 'utf8')).resolves.toBe(before)
    await expect(fs.stat(path.join(root, 'src', 'global.tailwind.css'))).rejects.toMatchObject({
      code: 'ENOENT',
    })
  })
})
